Vueの表示
tsubasa-ito/laravel8-vue pull request #5
Opened 2021-02-04 09:16 UTC by tsubasa-ito

Vueを正しく表示できるようになりました。

2021-02-04 10:10 UTC, kei-s16 requested changes
レビューリクエストありがとうございます！
挙動自体は大丈夫だと思いますが、細かい部分での指摘が多くなってしまったのでRequest Changesにします！

ご対応お願いします！

2021-02-04 10:10 UTC, k16em commented on docker/app/Dockerfile
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
Dockerfileいじってみるのめっちゃいいと思います！ 👍

2021-02-04 10:10 UTC, k16em commented on laravel/resources/js/components/ExampleComponent.vue
> +// console.log(messages.content);
![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
別の箇所でも同じ内容のレビューをしていますが、
- 動作確認用のログ出力
- 使わなくなった不要なコード

はコメントアウトではなく削除でお願いします！

2021-02-04 10:10 UTC, k16em commented on laravel/app/Http/Controllers/MessageController.php
> +        // return response()->json($messages);
![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
この部分、もう使わないコードをコメントアウトしているだけでしょうか？
そうであればコメントではなく削除でいいと思います！

2021-02-04 10:10 UTC, k16em commented on laravel/resources/views/message/index.blade.php
> +        </table> --}}
https://github.com/tsubasa-ito/laravel8-vue/blob/2e34ec96500133f4486ea28a949c5210d8904d29/laravel/resources/views/message/index.blade.php#L5-L22

![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
コメントアウトではなく削除対応でいいと思います！

2021-02-04 10:10 UTC, k16em commented on laravel/resources/views/message/index.blade.php
> +    {{-- @endif --}}
![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
↑と同じく、削除でいいと思います！

2021-02-04 10:10 UTC, k16em commented on laravel/routes/web.php
> +// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
https://github.com/tsubasa-ito/laravel8-vue/blob/2e34ec96500133f4486ea28a949c5210d8904d29/laravel/routes/web.php#L24-L28

![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
コメントアウトではなく削除でいい思います！

2021-02-04 12:27 UTC, 1t1nense1 approved these changes
一点だけコメントさせていただきましたが、vueコンポーネントの表示自体はできているのでapprove出しておきます 👍

2021-02-04 12:27 UTC, 1t1nense1 commented on laravel/resources/js/components/ExampleComponent.vue
> +}
![badge](https://img.shields.io/badge/review-nits-green.svg)
export ... がズレているので、今後このファイルをいじる時にでも直した方が良いかなと思いました！

2021-02-10 01:22 UTC, tsubasa-ito commented
コメントアウトのズレやカッコのズレなどを修正したので、確認よろしくお願いします。

2021-02-10 02:44 UTC, kei-s16 approved these changes
ご対応ありがとうございます！
細かな指摘が2点ありますが、Approveしておきます！
余裕があればマージ前にコメント内容の対応をお願いします！

2021-02-10 02:44 UTC, kei-s16 commented on laravel/app/Http/Controllers/MessageController.php
> +            // 'messages' => $messages
![NITS](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-NITS-green)
消し忘れでしょうか？
マージ前に削除お願いします！

2021-02-10 02:44 UTC, kei-s16 commented on laravel/routes/web.php
> +Route::get('/', 'MessageController@index')->name('message.index');
![IMO](https://img.shields.io/badge/%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC-IMO-FF69b4)
この部分ですが、下記とパスが重複しているみたいです
https://github.com/tsubasa-ito/laravel8-vue/blob/aecdfe7d67783aaaf6af7695bb453f952d26a000/laravel/routes/web.php#L16-L18

挙動的には下に書いたものが優先されると思うので、`app` ビューを返す処理が `MessageController` へ飛ばす処理が上書きされ、意図した動きになっているように見えます。
ですが、あとで自分や他の人が混乱しないように使わないほうの( `return view('app')` を指定している方の) Routeは削除したほうがいいかなと思いました

2021-02-10 02:50 UTC, tsubasa-ito commented on laravel/app/Http/Controllers/MessageController.php
> +            // 'messages' => $messages
消し忘れでしたので、消しておきました。

2021-02-10 02:51 UTC, tsubasa-ito commented on laravel/routes/web.php
> +Route::get('/', 'MessageController@index')->name('message.index');
理解しました。ありがとうございます！

2021-02-10 02:52 UTC, merged